### ISSUE TITLE
Topics index 页面排序有问题， topics show 页面分页有问题

### ISSUE THREAD

**Issue by aidewoode** [wppurking/ember-rc#1]
Hi， 刚才简单浏览了一些页面，发现了这两个问题。Topics index 页面排序的方向反了，在 Topics show 页面里面如果评论没有下一页的话，没有把 下一页的 button disable 掉

**Comment by aidewoode** [comment]
Hi， 刚才简单浏览了一些页面，发现了这两个问题。Topics index 页面排序的方向反了，在 Topics show 页面里面如果评论没有下一页的话，应该把 下一页的 button  disable 掉。

**Comment by wppurking** [comment]
- Topics index 那个是想的和代码的效果反了 ...
- 下一页我有想改, 其实我是准备把这些小细节问题专门统一一个时间改, 先处理大功能的.
